#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - python-swiftclient
    - rabbitmq-server

runcmd:
    - pip install Flask
    - git clone https://github.com/annanormark/Lab3_cloud.git
    - mv Lab3_cloud home/ubuntu/Lab3/
    - chmod -R 777 home/ubuntu/Lab3/
    - cd home/ubuntu/Lab3
    - pip install celery
    - pip install flower
    - sudo rabbitmqctl add_user an no
    - sudo rabbitmqctl add_vhost anno
    - sudo rabbitmqctl set_permissions -p anno ad ".*" ".*" ".*"
    - sudo -H -u ubuntu bash -c "python app.py &" 
    - sudo -H -u ubuntu bash -c "celery flower -A tasks &" 