#cloud-config

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - python-swiftclient

runcmd:
    - sudo pip install --upgrade pip
    - git clone https://github.com/annanormark/Lab3_cloud.git
    - mv Lab3_cloud home/ubuntu/Lab3
    - chmod -R 777 home/ubuntu/Lab3
    - cd home/ubuntu/Lab3/
    - pip install celery
    - sudo -H -u ubuntu bash -c "celery worker -A tasks &"